### ISSUE TITLE
Version information

### ISSUE THREAD

**Issue by debtanu09** [yuhc/gpu-rodinia#10]
Hello, please let me know which version of Rodinia is supported by CUDA 4.0 & GPGPUSim 3.2.2.
Better can you give a version to the version compatibility list between CUDA/GPGPUSim & Rodinia?
Thanks!

**Comment by yuhc** [comment]
Sorry I haven't tried it with GPGPUSim, but you can always change the SM version in https://github.com/yuhc/gpu-rodinia/blob/master/cuda/b%2Btree/Makefile#L4 to match the supported capabilities.

**Comment by debtanu09** [comment]
Thanks for the quick reply I'll try that.
One more thing, can you possibly have an archive for Rodinia 2.0 benchmark? The official download site shows error 403 when trying to download version 2.0 or 2.0.1

**Comment by yuhc** [comment]
You can find them at http://www.cs.virginia.edu/~kw5na/lava/Rodinia/Packages/Current/

**Comment by debtanu09** [comment]
Thank you very much man, you can close the case now.
You are very helpful, I highly appreciate it.
