### ISSUE TITLE
I cannot download the dateset from "http://lava.cs.virginia.edu/Rodinia/download_links.htm".

### ISSUE THREAD

**Issue by Mazhujun** [yuhc/gpu-rodinia#11]
Dear Auther,
  I want to use the benchmark of CUDA.But after I enter the website--http://lava.cs.virginia.edu/Rodinia/download_links.htm--and click the rodinia_3.1.tar.bz2(the other part will appear the same problem).The fig that can be seen will display.

<img width="910" alt="7a919ce15b393d70c514f81f54eda81" src="https://user-images.githubusercontent.com/74546019/143023190-04cab3d8-aab6-4eb8-abbe-2c5b793aa9cf.png">

Thus,where can I go to find the dateset?
Best wishes to you!
Thank you!

**Comment by Huangxt57** [comment]
Here seems to be a backup of the data of rodinia 3.1: https://github.com/JuliaParallel/rodinia/tree/master/data

**Comment by yuhc** [comment]
Thanks @Huangxt57! I uploaded my local copy to [Dropbox](https://www.dropbox.com/s/cc6cozpboht3mtu/rodinia-3.1-data.tar.gz?dl=0) with SHA-256 B90994D5208EC5A0A133DFB9. The size is double compared with `JuliaParallel/rodinia`, so not sure whether they are identical.
