### ISSUE TITLE
Run Kmeans with visual studio 2015

### ISSUE THREAD

**Issue by MajidSalimi** [yuhc/gpu-rodinia#2]
How can I compile and run kmeans with visual studio 2015?
I have linking errors!
please help me

**Comment by yuhc** [comment]
Hi, I didn't try it before, but you may follow these tutorials: [OpenCL on VS](https://medium.com/@pratikone/opencl-on-visual-studio-configuration-tutorial-for-the-confused-3ec1c2b5f0ca), [CUDA on Windows](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#system-requirements).
