### ISSUE TITLE
Input size limit for backprop

### ISSUE THREAD

**Issue by mahmoodn** [yuhc/gpu-rodinia#5]
I want to run rodinia on sm_60 and cuda-10.0. The default input size for backprop, 64k, is small for real hardware. When I run 1M elements, I get this error:

```
$ ./backprop 1048576
Random number generator seed: 7
Input layer size : 1048576
Starting training kernel
Performing GPU computation
bpnn kernel error: invalid configuration argument
```
Is there any way to fix that or the program is unable to handle that size?

**Comment by yuhc** [comment]
Hi, I'm not an expert in neural network, but I think it's possible to tune the code to use larger grid and thread size. Then you'll be able to use larger dataset.

(Related files:
https://github.com/yuhc/gpu-rodinia/blob/master/cuda/backprop/backprop_cuda.cu#L80
https://github.com/yuhc/gpu-rodinia/blob/master/cuda/backprop/facetrain.c#L19)

**Comment by mahmoodn** [comment]
Actually, 1048576 is divided by 16. So, I think it is a valid input size. However I don't know if the original author has limited his code to such size.
