### ISSUE TITLE
‘linear_congruential’ was not declared in this scope

### ISSUE THREAD

**Issue by mahmoodn** [yuhc/gpu-rodinia#6]
With gcc-4.8.5 I get this error while building graphgen
```
graphgen.cpp:31:36: error: ‘linear_congruential’ was not declared in this scope
 #define LINEAR_CONGRUENTIAL_ENGINE linear_congruential
```
In fact no where `linear_congruential` is defined based on my searches.

**Comment by yuhc** [comment]
Hi, line 29 in `data/bfs/inputGen/graphgen.cpp` gives the solution.
Please use `std::linear_congruential_engine` and `std::uniform_int_distribution` if you are using gcc.
