### ISSUE TITLE
Enlarging input size for cuda programs

### ISSUE THREAD

**Issue by mahmoodn** [yuhc/gpu-rodinia#7]
I need to enlarge the inputs. Not all applications are staright forward. For example, in `bfs`, I can create my own graph input. However, for b+ I don't know how to pick up the necessary parameters to enlarge. Any guide line?

**Comment by yuhc** [comment]
I guess the better way is to contact the original authors:

```
Ke Wang: kw5na@virginia.edu
Shuai Che: sc5nf@cs.virginia.edu
Kevin Skadron: skadron@cs.virginia.edu
```

I could help but I have lots of stuffs to do at this moment, sorry.
I am not one of the authors but host this repo for a project about OpenCL which is not under development.
