### ISSUE TITLE
Rodinia 3.1 compile dependencies?

### ISSUE THREAD

**Issue by theverytak** [yuhc/gpu-rodinia#8]
Thank you for your kind help in advance.

I'm trying to move on to Rodinia 3.1 from 3.0.
Is there any building dependencies on version 3.1? 
1. Does is support cuda 4.2?
2. Is there any specific gcc version that I need to use?

There are some info written regarding pervious version(2.3) but I can't find any updates for 3.1 version.

**Comment by yuhc** [comment]
I'm using cuda 10 to compile and run rodinia 3.1. GCC 5 works fine for me, but you may try newer versions of GCC.
However, you will have to modify a few makefiles to change the target architecture from sm_13 to sm_30. Otherwise the latest cuda versions can't support that deprecated architecture.

**Comment by theverytak** [comment]
Really appreciate your quick response. Gonna close this issue.
